### ISSUE TITLE
Youtube comments in dark mode turn white on hover

### ISSUE THREAD

**Issue by tudoramariei** [conversationai/perspective-viewership-extension#10]
Browser: Chrome 73
Tried with Tune turned off.
This is pretty much how it looks when this happens, part of a normal, dark comment above showing "View 9 replies": 
![Screenshot 2019-05-04 at 22 34 56](https://user-images.githubusercontent.com/2820084/57184043-04824a80-6ebe-11e9-917a-e9385a8742e5.png)

**Comment by JackHowa** [comment]
Had the same issue on twitter night mode as well 
![image](https://user-images.githubusercontent.com/5950956/57197299-40072e00-6f2b-11e9-8085-a483ce2d18bd.png)

**Comment by JackHowa** [comment]
Cool -- can jump into this. Think I found the offending class. Just a matter of authing the convo api and testing. 
<img width="1782" alt="Screen Shot 2019-10-05 at 6 54 47 PM" src="https://user-images.githubusercontent.com/5950956/66262225-d0c78b80-e7a1-11e9-909b-61745c166d16.png">

**Comment by JackHowa** [comment]
@tudoramariei let me know if you see fix #12 deployed and validated. Looks like the extension hasn't been updated yet ```Version
0.2.5 experimental
Updated
March 12, 2019``` via https://chrome.google.com/webstore/detail/tune-experimental/gdfknffdmmjakmlikbpdngpcpbbfhbnp

**Comment by JackHowa** [comment]
This has been updated. Let me know @rachelrosengoogle if I can help updating this version

**Comment by rachelrosengoogle** [comment]
Hi Jack, sorry about the delay. I'm looking into this now!

**Comment by tudoramariei** [comment]
@JackHowa Delayed checking back when you first sent the message because I didn't know what to look for
Just looked at the updated version and it's all 👌; YouTube comments look just fine 😄 
Thanks a lot for the work, if there's nothing else to be done, it's good to close

**Comment by rachelrosengoogle** [comment]
Yes, the new version is now up. Sorry for the delay, and thanks Jack for your contribution!

**Comment by JackHowa** [comment]
fantastic thank you -- looks good
