### ISSUE TITLE
the project does not build, any plan to fix it?

### ISSUE THREAD

**Issue by QuchenFu** [conversationai/perspective-viewership-extension#38]
The project is currently experiencing build issues, and it appears that all GitHub actions are also failing. any plan to fix it? Thanks @sorensenjs

**Comment by sorensenjs** [comment]
Hello QuchenFu - yes, acknowledging that this is currently broken, and that updating, particular Angular, to get back to a building state, to say nothing of getting back to a functioning state, is decidedly a not trivial change. Unfortunately we don't have any plans to fix this, and most of the original authors are no longer with our team for a variety of reasons. I did make an effort to give this a try but, as stated, it's not trivial. I would welcome and accept any pull requests that move this in the direction of being up to date.

**Comment by QuchenFu** [comment]
Thanks for the update and I wish you a happy christmas!
